### ISSUE TITLE
Standard now warns about any use of "var"

### ISSUE THREAD

**Issue by domoscargin** [alphagov/digitalmarketplace-govuk-frontend#208]
Running `npm run test` passes, but standard now flags all uses of "var" instead of let/const. Eventually, this will become an error rather than a warning: https://standardjs.com/changelog.html#1601---2020-10-30

We are using `var` in our components and `let/const` in our tests to follow the conventions of [govuk-frontend](https://github.com/alphagov/govuk-frontend).

Our options here include:

1. Rollback standard (it was bumped here: https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/205)
2. Update our code to use let/const instead of `var`
  * It looks like we do run our JS compile through Babel https://github.com/alphagov/digitalmarketplace-govuk-frontend/blob/0fc206d27fbf158fab526b0ad2cdf9ffca84d9cc/tasks/gulp/compile-assets.js#L55, so in theory this should work, but would require some effort and testing.
3. Ignore this rule as part of our standard/eslint config (https://standardjs.com/index.html#how-do-i-disable-a-rule)

**Comment by lfdebrux** [comment]
Thanks for creating an issue for this @domoscargin.

It might be worth talking to the Design System team and seeing what they think about this problem, seeing as they're going to be affected too. I'd be interested to know whether they are using `var` for a reason. I'm happy to reach out to them myself.

**Comment by lfdebrux** [comment]
@domoscargin beat me to it 😁 

https://github.com/alphagov/govuk-frontend/issues/2009

**Comment by domoscargin** [comment]
Closing as resolved by https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/229
